### ISSUE TITLE
Descriptor Sets managing

### ISSUE THREAD

**Issue by vertver** [NVIDIAGameWorks/NRI#15]
Recently ran into a problem with descriptor set management. I need to dynamically allocate and free sets in descriptor pool, but NRI does not have the necessary method to free descriptor sets. How do I need to manage these sets in this situation?

**Comment by dzhdanNV** [comment]
NRI has been designed to respect "create descriptor sets once, use many times" idiom. Of course, you can allocate sets on the fly, but there is not "free descriptor set" functionality, because it can introduce fragmentation of the descriptor pool, which implies complicated management under the hood (which contradicts the statement that NRI is a low level, low overhead GAPI abstraction layer). You can reset the entire "descriptor pool" instead. You can use several "descriptor pools" with different "update strategies". Some examples:
NRD sample (allocate once and use many times): https://github.com/NVIDIAGameWorks/NRDSample/blob/main/Source/NRDSample.cpp
NRI-based NRD integration layer (allocate on the fly):
https://github.com/NVIDIAGameWorks/RayTracingDenoiser/blob/master/Integration/NRDIntegration.hpp
If it doesn't work for you: please, describe your use case and the functionality you need (no promises though :)).

**Comment by vertver** [comment]
The problem is that without growable descriptor and memory pools, it's very difficult to manage and stream memory. NRI has the idiom "create once, use many times", but if that's the case - why can't I grow my memory pool or just create a new one and copy from the old one? For example, I want to have a big chunk of memory where I can allocate everything I need within that block. And when I try to add a new resource - I just can't, because the only way to unbind/bind the resource is to completely free up the entire memory descriptor.

If we are talking about memory management, there is also a very useful feature "tiled resources" which is also not supported in NRI. I plan to add this feature myself in the near future, after I sort out the resource allocation issues. 

Also, if you are interested, I may add a "Swap chain resize" feature. I did this because swap chain resize and destroy on DX11/DX12 is very rare and not recommended.

**Comment by dzhdanNV** [comment]
I see logic in your words but terminology is not right:
- `texture` and `buffer` are resources (ID3D12Resource)
- resources are bound to a `memory` heap (ID3D12Heap)
- `descriptor` is a light weight pointer to a resource with associated metadata

> why can't I grow my memory pool...

Any GAPI doesn't have such functionality. You need to wait for GPU idle and recreate...

> ...use sparse technique to manage allocations or just create a new one and copy from the old one

There is `CopyDescriptorSet` but in your case it's not very useful because there is no `DestroyDescriptorSet`. If we add this, we will bump into fragmentation headache, which we would like to avoid at all costs. Which problem you are trying to solve? As I mentioned earlier, you can create several descriptor pools:
- 1st is huge enough to work as a ring-buffer for N frames in flight
  - put all dynamic "I don't know what I'm rendering" stuff here
- 2nd is smaller and stores static descriptor sets
  - can be handy in post-processing, for example

If your renderer is render graph based, most likely you will need to use a couple of ring-buffer-like descriptor pools. IMO, it's simpler to accept minor inefficiency of growable (statically allocated ring-buffer) descriptor pools, than to try to implement a monstrous system which manages descriptors allowing and fighting with fragmentation at runtime.

> Tiled resources...

Yes, would be nice to have. If you implement support even only for D3D12, we will be happy to adopt your changes ;)

> Also, if you are interested, I may create a "Swap chain resize" PR. It replaces swap chain recreation to DXGI ResizeBuffers on 
DX11/DX12.

Yes, please \O/
