### ISSUE TITLE
ReBAR and sparse texture support

### ISSUE THREAD

**Issue by vertver** [NVIDIAGameWorks/NRI#24]
I was thinking about adding support for Resizeable BAR, but it is only supported in Vulkan and D3D12. What do you think about creating an additional interface for sparse textures and ReBAR as an extension. I would implement one of them, but without an interface I have no idea how to implement them in NRI. 

Maybe we need something like "resource extension"? We can easily combine both of technologies into one interface and maybe add streaming support and other features that are not presented on D3D11.

**Comment by vertver** [comment]
Also, AFAIK, you don't need to have ReBAR support to work with BAR on Vulkan (just use a separate heap with HOST_VISIBLE flag)

**Comment by vertver** [comment]
Also, on D3D12 there is a thing: https://learn.microsoft.com/en-us/windows/win32/direct3d12/default-texture-mapping

**Comment by dzhdanNV** [comment]
Hi! Thanks for your interest! I would suggest closing this issue and opening two new instead:
- ReBAR support (most likely core)
- sparse texture support (most likely extension)

IMO, these are two orthogonal things (but 1st can help 2nd).

At this moment I don't know "sparse texture" API at all for both VK and D3D12, but this problem is solvable. You can start propose an extension API to make the discussion more specific. There are people who can help.

Regarding ReBAR:

Some notes first:
- it looks like ReBAR is not enabled in BIOS on your system, because if it's enabled you will get 2 heaps reported :) but the main one will have more "memory types" associated with it
- a few moments ago I improved logging of information about available memory heaps, now it looks like:
```
NRI::VULKAN::NVIDIA GeForce RTX 4080 - Memory heaps:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #0: 16064 Mb - DEVICE_LOCAL_BIT 
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #1: 32612 Mb - *SYSMEM* 
NRI::VULKAN::NVIDIA GeForce RTX 4080 - Memory types:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #1:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -     *SYSMEM* 
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #0:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -     DEVICE_LOCAL_BIT 
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #1:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -     HOST_VISIBLE_BIT HOST_COHERENT_BIT 
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #1:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -     HOST_VISIBLE_BIT HOST_COHERENT_BIT HOST_CACHED_BIT 
NRI::VULKAN::NVIDIA GeForce RTX 4080 -   Heap #0:
NRI::VULKAN::NVIDIA GeForce RTX 4080 -     DEVICE_LOCAL_BIT HOST_VISIBLE_BIT HOST_COHERENT_BIT 
```
It seems to me that extending `MemoryLocation` should be enough to bring ReBAR support:
```
NRI_ENUM
(
    MemoryLocation, uint8_t,

    DEVICE,
    DEVICE_HOST_VISIBLE, <====== add something like this
    HOST_UPLOAD,
    HOST_READBACK,

    MAX_NUM
);
```
How to add support:
- VK: native, just use special memory type, should not be difficult to add
- D3D11: only via NV API (it's already there)
- D3D12: only via NV API (not there yet)

I think AMD has exposed something similar in AMD AGS, I don't mind hooking it too (AMD AGS is already in D3D11)
