### ISSUE TITLE
Expose `AreEnhancedBarriersSupported` in device's desc

### ISSUE THREAD

**Issue by 01Pollux** [NVIDIAGameWorks/NRI#69]
Basically as the title says, it would be useful to have it exported to `nri::DeviceDesc`. it'll be used to correctly check between two acces stages / layout access stages for buffers and textures to cull and avoid transition to the same state.

Currently used in:
```CPP
bool ResourceStateTracker::AreStateEqual(
    nri::AccessStage A,
    nri::AccessStage B) const
{
    switch (m_DeviceDesc->graphicsAPI)
    {
    case nri::GraphicsAPI::D3D12:
    {
        // if (!m_DeviceDesc->areEnhancedBarriersSupported)
        {
            // Using legacy barriers, ID3D12GraphicsCommandList::ResourceBarrier does not support layout transitions
            return A.access== B.access;
        }
    }
        [[fallthrough]];
    case nri::GraphicsAPI::VULKAN:
    {
        return A.access == B.access &&
               A.stages == B.stages;
    }
    }
    return false;
}

bool ResourceStateTracker::AreStateEqual(
    const nri::AccessLayoutStage& A,
    const nri::AccessLayoutStage& B) const
{
    switch (m_DeviceDesc->graphicsAPI)
    {
    case nri::GraphicsAPI::D3D12:
    {
        //if (!m_DeviceDesc->areEnhancedBarriersSupported)
        {
            // Using legacy barriers, ID3D12GraphicsCommandList::ResourceBarrier does not support layout transitions
            return A.access== B.access;
        }
    }
        [[fallthrough]];
    case nri::GraphicsAPI::VULKAN:
    {
        return A.access == B.access &&
               A.stages == B.stages &&
               A.layout == B.layout;
    }
    }
    return false;
}
```
If i check all members while using legacy barriers, the results are 'incorrect' and will trigger
`D3D12 ERROR: ID3D12CommandList::ResourceBarrier: Before and after states must be different. [ RESOURCE_MANIPULATION ERROR #525: RESOURCE_BARRIER_MATCHING_STATES]`

**Comment by dzhdanNV** [comment]
Thanks, Yassine. It had been my plan to expose this, but I decided not doing it because I assumed that using "just VK style" barriers should cover all cases. But I'm seeing that you have bumped into an issue, so I don't mind to expose `areEnchancedBarriersSupported` (most likely will be `isEnchancedBarrierSupported`, I don't think that plural form is needed):
- D3D11: `isEnchancedBarrierSupported = false`
- D3D12: `isEnchancedBarrierSupported = check real support`
- VK: `isEnchancedBarrierSupported = true`

**Comment by dzhdanNV** [comment]
Done!
